config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 get 'new' => 'books#new'

 get 'top' => 'books#top'

 post 'books' => 'books#create'

 get 'books'=> 'books#index', as: 'back'

 get 'books/:id' => 'books#show', as: 'book'

 get 'books/:id/edit' => 'books#edit', as: 'edit_book'

 patch 'books/:id' => 'books#update', as: 'update_book'

delete 'books/:id' => 'books#destroy', as: 'destroy_book'

 

root to: "books#top"


#resources :books


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def  top
  end

  def new

     @book = Book.new

  end

 def create
        # ストロングパラメーターを使用
         @book = Book.new(book_params)
         if @book.save
          flash[:notice] ="successfully"
        redirect_to book_path(@book)
      else
        render :index

      end
  end







def index
	@books = Book.all
  @book = Book.new
end

def edit
        @book = Book.find(params[:id])
 end

def show
  @book = Book.find(params[:id])

end

def update
  @book = Book.find(params[:id])
    @book.update(book_params)
 if @book.save
 flash[:notice] ="successfully"
 redirect_to book_path(@book)
 else
 render :index

end
end

  def destroy
          book = Book.find(params[:id])
          book.destroy
          redirect_to books_path


        end



 private
 def book_params
	params.require(:book).permit(:title, :body)

 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_for部分 -->

<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_field :body %>

    <p><%= f.submit 'Update Book' %></p>
<% end %>


<p>
 <%= link_to "Show", book_path %>
|
 <%= link_to "Back", back_path %>
</p>

app/views/books/index.html.erb
	 

	<h1>Books</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.title %></td>
				<td><%= book.body %></td>
				<td><%= link_to "Show", book_path(book) %></td>
				<td><%= link_to "Edit", edit_book_path(book) %></td>
				<td><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
			</tr>
		<% end %>
	</tbody>
</table>


<h2>New book</h2>

<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>Books</h1>








<h1>New book</h1>

<%= form_for(@book) do |f| %>

<h4>Title</h4>
    <%= f.text_field :title %>

   <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>






<% end %>



to

app/views/books/show.html.erb
<p><strong>Title:</strong>
<%= @book.title %></p>
<p><strong>Body:</strong>
spec<%= @book.body %></p>



<p>
 <%= link_to "Edit", edit_book_path %>
|
 <%= link_to "Back", back_path %>
</p>

app/views/books/top.html.erb
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">.turbolinks-progress-bar {
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  background: #0076ff;
  z-index: 9999;
  transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
  transform: translate3d(0, 0, 0);}
　　</style>
<link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">

<script src="/assets/application-4e370d3723b6f204426a9414077d365ea07814cce5619ae24fb7e581988f19ed.js" data-turbolinks-track="reload"></script>

<title>WebCampBackendNew</title>

<meta name="csrf-param" content="authenticity_token">

<meta name="csrf-token" content="N4U9MV5u4Bo+E/jhWYqxbtVocC/lP+0NJ+R/D+q48WUYP/6Nze/G8vBmv7yet9oUuUROwSNpr9PNobagBOPWaA==">
</head>
<body>

<h1>
ようこそ
<strong>Bookers</strong>
   へ！
</h1>


<p><strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="flash">
    <%= flash[:notice] %>
    </div>
    <% end %>

    <%= yield %> 
  </body>
</html>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/root/top.html.erb
<h1>ようこそ Bookers へ！</h1>